### ISSUE TITLE
Fatal error: Uncaught Error: Cannot unset string offsets

### ISSUE THREAD

**Issue by onliniak** [indieweb/wordpress-micropub#186]
WordPress 5.0.3
PHP 7.3.1
Micropublish.net

There was an error making a request to your Micropub endpoint. The error received was: Fatal error: Uncaught Error: Cannot unset string offsets in wp-content/plugins/micropub/includes/class-micropub-error.php:71 Stack trace: #0 /wp-content/plugins/micropub/includes/class-micropub-endpoint.php(964): micropub_wp_error(Object(WP_Error)) #1 /wp-content/plugins/micropub/includes/class-micropub-endpoint.php(460): Micropub_Endpoint::check_error(Object(WP_Error)) #2 /wp-content/plugins/micropub/includes/class-micropub-endpoint.php(254): Micropub_Endpoint::create(1) #3 /wp-includes/rest-api/class-wp-rest-server.php(936): Micropub_Endpoint::post_handler(Object(WP_REST_Request)) #4 /wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request)) #5 /wp-includes/re in /wp-content/plugins/micropub/includes/class-micropub-error.php on line 71

**Comment by onliniak** [comment]
Sorry, my fault.

It was conflict with OpenID plugin.

**Comment by onliniak** [comment]
Sorry, my fault it was conflict with another (depreciated) plugin.
